.TH "COTACAO" "1" "January 2017" "2.0.2" "cotacao manual"
.SH "NAME"
\fBcotacao\fR - Cotações da Bolsa de Valores
.SH "SYNOPSIS"
.P
\fBcotacao\fR \[lB]\fBoptions\fR\[rB] <\fIativo\fR>
.SH "DESCRIPTION"
.P
Busca informações de um ativo na Bolsa de Valores.
.SH "OPTIONS"
.SS "\fB-h\fR, \fB--help\fR"
.P
.RS 2
.nf
cotacao --help
.fi
.RE
.P
Output short usage information.
.SS "\fB-v\fR, \fB--version\fR"
.P
.RS 2
.nf
cotacao --version
.fi
.RE
.P
Output CLI version number.
.SH "USAGE"
.P
.RS 2
.nf
cotacao "vale3"
.fi
.RE
.SH "DIAGNOSTICS"
.P
\fBcotacao\fR exits 0 on success, and 1 otherwise.
.SH "BUGS"
.P
\fI\(lahttps://github.com/lagden/stock-quote/issues\(ra\fR
.SH "AUTHOR"
.P
Written by Thiago Lagden \fBmailto:lagden@gmail.com\fR \fI\(lalagden@gmail.com\(ra\fR
